# Generated by Django 5.2.17 on 2026-09-23 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume_analysis', '0002_resumeanalysis_achievements_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=160)),
                ('job_title', models.CharField(max_length=160)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('job_url', models.URLField(blank=True)),
                ('date_applied', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Wishlist', 'Wishlist'), ('Applied', 'Applied'), ('Assessment', 'Assessment'), ('Interview', 'Interview'), ('Offer', 'Offer'), ('Rejected', 'Rejected')], default='Wishlist', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('salary_range', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=160)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('job_description', models.TextField()),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('breakdown', models.JSONField(default=dict)),
                ('matched_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('keywords', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume_analysis.resumeanalysis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('difficulty', models.CharField(max_length=30)),
                ('skills', models.JSONField(default=list)),
                ('problem_statement', models.TextField()),
                ('features', models.JSONField(default=list)),
                ('tech_stack', models.JSONField(default=list)),
                ('expected_outcome', models.TextField()),
                ('portfolio_value', models.TextField()),
                ('status', models.CharField(default='Saved', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
