# Generated by Django 5.2.17 on 2026-09-23 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(choices=[('AI Engineer', 'AI Engineer'), ('Machine Learning Engineer', 'Machine Learning Engineer'), ('Data Analyst', 'Data Analyst'), ('Data Scientist', 'Data Scientist'), ('Software Engineer', 'Software Engineer'), ('QA Engineer', 'QA Engineer'), ('ServiceNow Developer', 'ServiceNow Developer'), ('Business Analyst', 'Business Analyst')], default='Software Engineer', max_length=80)),
                ('bio', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
