# Generated by Django 5.2.17 on 2026-09-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_role',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='portfolio_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='target_role',
            field=models.CharField(choices=[('AI Engineer', 'AI Engineer'), ('Machine Learning Engineer', 'Machine Learning Engineer'), ('Data Analyst', 'Data Analyst'), ('Data Scientist', 'Data Scientist'), ('Software Engineer', 'Software Engineer'), ('Java Developer', 'Java Developer'), ('Python Developer', 'Python Developer'), ('QA Automation Engineer', 'QA Automation Engineer'), ('ServiceNow Developer', 'ServiceNow Developer'), ('Business Analyst', 'Business Analyst'), ('Cloud Engineer', 'Cloud Engineer'), ('DevOps Engineer', 'DevOps Engineer'), ('Cybersecurity Analyst', 'Cybersecurity Analyst')], default='Software Engineer', max_length=80),
        ),
    ]
